version: '3.8'

services:
  app1:
    image: command1
    ports:
      - "9091:9091"

  app2:
    image: command2
    ports:
      - "10001:10001"

  app3:
    image: command3
    ports:
      - "11011:11011"

  nginx:
    image: nginx:latest
    container_name: nginx-command
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    restart: always
