apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-hub-k8s-demo-deployment-3
  labels:
    app: docker-k8s-service-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-service-3
  template:
    metadata:
      labels:
        app: docker-k8s-service-3
    spec:
      containers:
        - name: docker-k8s-service-3
          image: quang227296/service-3-hub
          ports:
            - containerPort: 8083
